### ISSUE TITLE
Cmake error when installing.

### ISSUE THREAD

**Issue by pablodalma93** [google/monster-mash#18]
I'm getting this error when installing. Not sure if it's an error in the steps of the installation or a result of my lack of knowledge in Linux. Installed Linux in Virtualbox to try the program. 

Cmake error at CmakeLists.txt

The Cmake_C Compiler.

Path_to_emsdk/upstream/emscripten/emcc

is not a full path and was not found in path

Tell Cmake where to find the compiler by setting
either the enviroment variable "CC" or the Cmake 
cache entry CMAKE_C_COMPILER to the full path to 
the compiler, or to the compiler name if it is in
the PATH.

**Comment by LearnToStick** [comment]
Maybe you can   try to replace all PATH_TO_EMSDK with the path to your emsdk directory.

**Comment by pablodalma93** [comment]
> 
I fixed it some days ago. If I recall correctly this was for the desktop version. Now it runs but it only shows a grey screen with the title of the software. Any idea?

**Comment by LearnToStick** [comment]
At present, I still haven't built the web version successfully, and I haven't tried the desktop version. May I ask if you built it on a linux system or a windows system?

**Comment by LearnToStick** [comment]
![image](https://user-images.githubusercontent.com/33288475/158190814-aab37ed0-fd8e-490e-a296-e3e468b7c534.png)
success！you can see the demo ,help button can help you !

**Comment by pablodalma93** [comment]
> At present, I have successfully configured the desktop version, which is the same as yours, without any buttons, only draw，like this ![image](https://user-images.githubusercontent.com/33288475/158189824-8276d808-d26a-430f-b3e0-cca997fa3d75.png)

Nevermind, I managed to make the web version work. Thanks for the reply anyway.

**Comment by helderdaniel** [comment]
@pablodalma93 how did you make the web version work? I tried to compile in ubuntu but I still have this [issue Can't run properly #20](https://github.com/google/monster-mash/issues/20)

**Comment by helderdaniel** [comment]
Found how to run it.
It must be ran through a web server and it is needed to copy some more files than the ones generated in the build directory.
Take a look at the end of this [comment](https://github.com/google/monster-mash/issues/1#issuecomment-854153041)
